# Generated by Django 3.1.3 on 2021-10-26 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AssetsRegistry', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departmentitem',
            old_name='category',
            new_name='department',
        ),
    ]
