# Generated by Django 3.1.3 on 2021-03-24 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='admin',
            new_name='is_admin',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='pending',
            new_name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='staff',
        ),
    ]
