# Generated by Django 3.1.3 on 2021-11-02 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=130)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=130)),
            ],
            options={
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=130)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GeneralLedger.department')),
            ],
            options={
                'verbose_name_plural': 'Stations',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=130)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GeneralLedger.category')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralLedger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug_number', models.SlugField(blank=True, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, max_length=1250)),
                ('Amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('YearNow', models.CharField(default='2023/2024', max_length=25)),
                ('QuarterNow', models.CharField(default='Q1', max_length=25)),
                ('item_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GeneralLedger.category')),
                ('item_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GeneralLedger.item')),
            ],
            options={
                'verbose_name_plural': 'General Ledgers',
            },
        ),
        migrations.CreateModel(
            name='DepartmentGeneralLedger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug_number', models.SlugField(blank=True, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, max_length=1250)),
                ('Amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('YearNow', models.CharField(default='2023/2024', max_length=25)),
                ('QuarterNow', models.CharField(default='Q1', max_length=25)),
                ('item_department_gl', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GeneralLedger.department')),
                ('item_dept_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GeneralLedger.category')),
                ('item_dept_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GeneralLedger.item')),
                ('item_station_gl', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GeneralLedger.station')),
            ],
            options={
                'verbose_name_plural': 'Department General Ledgers',
            },
        ),
    ]
