# Generated by Django 2.2.1 on 2021-04-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralLedger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug_number', models.SlugField(blank=True, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('item_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('partner', models.CharField(max_length=120)),
                ('invoice', models.CharField(max_length=255)),
                ('transaction_ref_number', models.CharField(max_length=255)),
                ('account_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=255)),
                ('date_due', models.DateTimeField()),
                ('debit', models.DecimalField(decimal_places=2, max_digits=20)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=20)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('paye_amt', models.CharField(max_length=255)),
                ('invoice_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('balanced', models.BooleanField(default=True)),
            ],
        ),
    ]
