# Generated by Django 2.2.1 on 2021-04-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeneralLedger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalledger',
            name='date_due',
            field=models.DateTimeField(verbose_name='dd-mm-yyyy'),
        ),
    ]
