# Generated by Django 3.1.3 on 2021-03-29 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GeneralLedger', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalledger',
            old_name='paye',
            new_name='paye_amt',
        ),
    ]
