# Generated by Django 2.2.1 on 2021-04-03 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeneralLedger', '0002_auto_20210403_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalledger',
            name='date_due',
            field=models.DateField(verbose_name='dd-mm-yyyy'),
        ),
    ]
