# Generated by Django 3.1.3 on 2021-03-29 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeneralLedger', '0002_auto_20210329_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalledger',
            name='credit',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='generalledger',
            name='debit',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='generalledger',
            name='invoice_amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='generalledger',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
