# Generated by Django 2.2.1 on 2021-04-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeneralLedger', '0003_auto_20210403_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalledger',
            name='date_due',
            field=models.DateField(),
        ),
    ]
