# Generated by Django 2.2.1 on 2021-04-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeneralLedger', '0004_auto_20210403_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalledger',
            name='date_due',
            field=models.CharField(max_length=25),
        ),
    ]
