# Generated by Django 2.2.1 on 2021-04-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeneralLedger', '0005_auto_20210405_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalledger',
            name='currency',
            field=models.CharField(choices=[('Kshs', 'Shillings'), ('Dollars', 'Dollars'), ('Pounds', 'Pounds')], default='Kshs', max_length=25),
        ),
    ]
