# Generated by Django 2.2.1 on 2021-04-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeneralLedger', '0006_generalledger_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalledger',
            name='credit',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='generalledger',
            name='debit',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='generalledger',
            name='invoice_amount',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='generalledger',
            name='tax_amount',
            field=models.CharField(max_length=20),
        ),
    ]
