# Generated by Django 2.2.1 on 2021-04-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeneralLedger', '0007_auto_20210413_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalledger',
            name='credit',
            field=models.DecimalField(decimal_places=2, max_digits=25),
        ),
        migrations.AlterField(
            model_name='generalledger',
            name='debit',
            field=models.DecimalField(decimal_places=2, max_digits=25),
        ),
        migrations.AlterField(
            model_name='generalledger',
            name='invoice_amount',
            field=models.DecimalField(decimal_places=2, max_digits=25),
        ),
        migrations.AlterField(
            model_name='generalledger',
            name='paye_amt',
            field=models.DecimalField(decimal_places=2, max_digits=25),
        ),
        migrations.AlterField(
            model_name='generalledger',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, max_digits=25),
        ),
    ]
